### ISSUE TITLE
Just want to make sure No booking with you.

### ISSUE THREAD

**Issue by kanjamad** [fvcproductions/ama#2]
Hi Frances
Hope you’re doing well.
I was booking on Wednesday 19th at 12.30pm for advice about after 1week at bootcamp UC Berkeley.
But I didn’t pay the appropriate amount before the session.

Just want to make sure that means I don’t have schedule with you.

Thank you
Kanjamad Bosel

**Comment by FrancesCoronel** [comment]
Hi @kanjamad - it looks like you re-scheduled for September 26th. And no worries, I'm not going to charge for this session. 😊
